//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""d048dd87-e634-460b-aaf5-b82f2104ca65"",
            ""actions"": [
                {
                    ""name"": ""MoveInput"",
                    ""type"": ""Value"",
                    ""id"": ""856f876a-597a-4982-bd71-f4a563828fef"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SweepInput"",
                    ""type"": ""Button"",
                    ""id"": ""41fb8a5a-4716-4629-9523-0fe1dee844b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwipeInput"",
                    ""type"": ""Button"",
                    ""id"": ""b5141167-00af-4d55-b9ad-12f39ee89e2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashInput"",
                    ""type"": ""Button"",
                    ""id"": ""493a177a-5f16-47b8-b79e-82891ed6d1fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EscapeTrashBallInput"",
                    ""type"": ""Button"",
                    ""id"": ""a49fb0ae-fa53-45dd-be0b-c564aa32df92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMoveInput"",
                    ""type"": ""Value"",
                    ""id"": ""eab0adb6-caa3-4262-baec-b6137a4b5ccb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ControllerAimInput"",
                    ""type"": ""Value"",
                    ""id"": ""77e92c7f-7476-42ab-855e-4497f027aca3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone(min=0.01,max=0.01)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""InteractionInput"",
                    ""type"": ""Button"",
                    ""id"": ""17a6926a-cca0-400b-9fd1-d602aa64dc38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HookInput"",
                    ""type"": ""Button"",
                    ""id"": ""9d43670a-6f30-4ab9-8b23-678d279737f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9464c060-2fdd-4f1e-acd4-7d57def65977"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""56f5b2b1-53b9-4577-b9d6-f14ca171ff67"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7aa2fb6f-db09-4cc8-b2ff-69ab7154b907"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""34c062c4-36e1-4c57-ad84-c7795020dde8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4341879b-429a-407a-ade0-edf1078b2d7c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e8e10cf3-ad99-491e-88a6-228c8d12e5c1"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fa3416ed-515c-4b63-a858-f56f1132afd7"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""53e2f6c4-57e1-4583-b343-88c6e2d9a094"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""435ebaef-1fc9-4d12-9391-eb2d1260b771"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7e9810f1-5245-4e88-8433-1e310fc9fef0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""faa085cc-147e-4b2c-ac89-5e6067175a13"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afcbd910-5aa2-472a-a823-e22d63203cb1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SweepInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9818e213-78e5-41dd-a8ea-f010a39e7840"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SweepInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5aacc2f-1881-4e70-aee1-c11e3145c193"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d56a948e-e88b-4596-a8b6-00afedd944a3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b6770df-161c-4e2e-80f0-b09e98dcc704"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""165c05fa-be5c-422f-a750-94bfce61eeed"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6e423a5-4d0a-4660-85c7-15eee2030539"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fb830fd-5d7e-4e84-8529-55b4bbddda2d"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ad0e07b-30f5-459c-80fd-1c08c5eb097a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeTrashBallInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fc1db03-e33b-4f83-8bef-9dfb89753e13"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeTrashBallInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fec7c77-0448-4c86-845d-93e86be57a55"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeTrashBallInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d4655bb-2d60-4667-92f5-0de9a304d4a4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeTrashBallInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""122b20a6-f5d0-4d36-bca3-e398fb80e57c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeTrashBallInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81ee45fe-4397-4fd1-ad2a-6456ace2a858"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractionInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51990bf9-4093-4423-a83b-9671e0bc1647"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractionInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76d7bec7-fac0-4865-aee9-679b3ce4bcae"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HookInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6af02e2-9711-4685-9729-6327b35107cf"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HookInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""824cad68-63d4-414a-9e3f-a3fcf1e4eeec"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerAimInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_MoveInput = m_Default.FindAction("MoveInput", throwIfNotFound: true);
        m_Default_SweepInput = m_Default.FindAction("SweepInput", throwIfNotFound: true);
        m_Default_SwipeInput = m_Default.FindAction("SwipeInput", throwIfNotFound: true);
        m_Default_DashInput = m_Default.FindAction("DashInput", throwIfNotFound: true);
        m_Default_EscapeTrashBallInput = m_Default.FindAction("EscapeTrashBallInput", throwIfNotFound: true);
        m_Default_MouseMoveInput = m_Default.FindAction("MouseMoveInput", throwIfNotFound: true);
        m_Default_ControllerAimInput = m_Default.FindAction("ControllerAimInput", throwIfNotFound: true);
        m_Default_InteractionInput = m_Default.FindAction("InteractionInput", throwIfNotFound: true);
        m_Default_HookInput = m_Default.FindAction("HookInput", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_MoveInput;
    private readonly InputAction m_Default_SweepInput;
    private readonly InputAction m_Default_SwipeInput;
    private readonly InputAction m_Default_DashInput;
    private readonly InputAction m_Default_EscapeTrashBallInput;
    private readonly InputAction m_Default_MouseMoveInput;
    private readonly InputAction m_Default_ControllerAimInput;
    private readonly InputAction m_Default_InteractionInput;
    private readonly InputAction m_Default_HookInput;
    public struct DefaultActions
    {
        private @PlayerControls m_Wrapper;
        public DefaultActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveInput => m_Wrapper.m_Default_MoveInput;
        public InputAction @SweepInput => m_Wrapper.m_Default_SweepInput;
        public InputAction @SwipeInput => m_Wrapper.m_Default_SwipeInput;
        public InputAction @DashInput => m_Wrapper.m_Default_DashInput;
        public InputAction @EscapeTrashBallInput => m_Wrapper.m_Default_EscapeTrashBallInput;
        public InputAction @MouseMoveInput => m_Wrapper.m_Default_MouseMoveInput;
        public InputAction @ControllerAimInput => m_Wrapper.m_Default_ControllerAimInput;
        public InputAction @InteractionInput => m_Wrapper.m_Default_InteractionInput;
        public InputAction @HookInput => m_Wrapper.m_Default_HookInput;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @MoveInput.started += instance.OnMoveInput;
            @MoveInput.performed += instance.OnMoveInput;
            @MoveInput.canceled += instance.OnMoveInput;
            @SweepInput.started += instance.OnSweepInput;
            @SweepInput.performed += instance.OnSweepInput;
            @SweepInput.canceled += instance.OnSweepInput;
            @SwipeInput.started += instance.OnSwipeInput;
            @SwipeInput.performed += instance.OnSwipeInput;
            @SwipeInput.canceled += instance.OnSwipeInput;
            @DashInput.started += instance.OnDashInput;
            @DashInput.performed += instance.OnDashInput;
            @DashInput.canceled += instance.OnDashInput;
            @EscapeTrashBallInput.started += instance.OnEscapeTrashBallInput;
            @EscapeTrashBallInput.performed += instance.OnEscapeTrashBallInput;
            @EscapeTrashBallInput.canceled += instance.OnEscapeTrashBallInput;
            @MouseMoveInput.started += instance.OnMouseMoveInput;
            @MouseMoveInput.performed += instance.OnMouseMoveInput;
            @MouseMoveInput.canceled += instance.OnMouseMoveInput;
            @ControllerAimInput.started += instance.OnControllerAimInput;
            @ControllerAimInput.performed += instance.OnControllerAimInput;
            @ControllerAimInput.canceled += instance.OnControllerAimInput;
            @InteractionInput.started += instance.OnInteractionInput;
            @InteractionInput.performed += instance.OnInteractionInput;
            @InteractionInput.canceled += instance.OnInteractionInput;
            @HookInput.started += instance.OnHookInput;
            @HookInput.performed += instance.OnHookInput;
            @HookInput.canceled += instance.OnHookInput;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @MoveInput.started -= instance.OnMoveInput;
            @MoveInput.performed -= instance.OnMoveInput;
            @MoveInput.canceled -= instance.OnMoveInput;
            @SweepInput.started -= instance.OnSweepInput;
            @SweepInput.performed -= instance.OnSweepInput;
            @SweepInput.canceled -= instance.OnSweepInput;
            @SwipeInput.started -= instance.OnSwipeInput;
            @SwipeInput.performed -= instance.OnSwipeInput;
            @SwipeInput.canceled -= instance.OnSwipeInput;
            @DashInput.started -= instance.OnDashInput;
            @DashInput.performed -= instance.OnDashInput;
            @DashInput.canceled -= instance.OnDashInput;
            @EscapeTrashBallInput.started -= instance.OnEscapeTrashBallInput;
            @EscapeTrashBallInput.performed -= instance.OnEscapeTrashBallInput;
            @EscapeTrashBallInput.canceled -= instance.OnEscapeTrashBallInput;
            @MouseMoveInput.started -= instance.OnMouseMoveInput;
            @MouseMoveInput.performed -= instance.OnMouseMoveInput;
            @MouseMoveInput.canceled -= instance.OnMouseMoveInput;
            @ControllerAimInput.started -= instance.OnControllerAimInput;
            @ControllerAimInput.performed -= instance.OnControllerAimInput;
            @ControllerAimInput.canceled -= instance.OnControllerAimInput;
            @InteractionInput.started -= instance.OnInteractionInput;
            @InteractionInput.performed -= instance.OnInteractionInput;
            @InteractionInput.canceled -= instance.OnInteractionInput;
            @HookInput.started -= instance.OnHookInput;
            @HookInput.performed -= instance.OnHookInput;
            @HookInput.canceled -= instance.OnHookInput;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnMoveInput(InputAction.CallbackContext context);
        void OnSweepInput(InputAction.CallbackContext context);
        void OnSwipeInput(InputAction.CallbackContext context);
        void OnDashInput(InputAction.CallbackContext context);
        void OnEscapeTrashBallInput(InputAction.CallbackContext context);
        void OnMouseMoveInput(InputAction.CallbackContext context);
        void OnControllerAimInput(InputAction.CallbackContext context);
        void OnInteractionInput(InputAction.CallbackContext context);
        void OnHookInput(InputAction.CallbackContext context);
    }
}
