//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""d048dd87-e634-460b-aaf5-b82f2104ca65"",
            ""actions"": [
                {
                    ""name"": ""MoveInput"",
                    ""type"": ""Value"",
                    ""id"": ""856f876a-597a-4982-bd71-f4a563828fef"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SweepInput"",
                    ""type"": ""Button"",
                    ""id"": ""41fb8a5a-4716-4629-9523-0fe1dee844b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwipeInput"",
                    ""type"": ""Button"",
                    ""id"": ""b5141167-00af-4d55-b9ad-12f39ee89e2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashInput"",
                    ""type"": ""Button"",
                    ""id"": ""493a177a-5f16-47b8-b79e-82891ed6d1fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EscapeTrashBallInput"",
                    ""type"": ""Button"",
                    ""id"": ""a49fb0ae-fa53-45dd-be0b-c564aa32df92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMoveInput"",
                    ""type"": ""Value"",
                    ""id"": ""eab0adb6-caa3-4262-baec-b6137a4b5ccb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDeltaInput"",
                    ""type"": ""Value"",
                    ""id"": ""80df9cb6-de67-4daa-8513-7fd9f313c3d0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone(min=0.01,max=0.01)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9464c060-2fdd-4f1e-acd4-7d57def65977"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""56f5b2b1-53b9-4577-b9d6-f14ca171ff67"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7aa2fb6f-db09-4cc8-b2ff-69ab7154b907"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""34c062c4-36e1-4c57-ad84-c7795020dde8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4341879b-429a-407a-ade0-edf1078b2d7c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""afcbd910-5aa2-472a-a823-e22d63203cb1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SweepInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5aacc2f-1881-4e70-aee1-c11e3145c193"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d56a948e-e88b-4596-a8b6-00afedd944a3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""165c05fa-be5c-422f-a750-94bfce61eeed"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""860a2e37-c5fd-4650-8063-a08a51ba89dc"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDeltaInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6e423a5-4d0a-4660-85c7-15eee2030539"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ad0e07b-30f5-459c-80fd-1c08c5eb097a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeTrashBallInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_MoveInput = m_Default.FindAction("MoveInput", throwIfNotFound: true);
        m_Default_SweepInput = m_Default.FindAction("SweepInput", throwIfNotFound: true);
        m_Default_SwipeInput = m_Default.FindAction("SwipeInput", throwIfNotFound: true);
        m_Default_DashInput = m_Default.FindAction("DashInput", throwIfNotFound: true);
        m_Default_EscapeTrashBallInput = m_Default.FindAction("EscapeTrashBallInput", throwIfNotFound: true);
        m_Default_MouseMoveInput = m_Default.FindAction("MouseMoveInput", throwIfNotFound: true);
        m_Default_MouseDeltaInput = m_Default.FindAction("MouseDeltaInput", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_MoveInput;
    private readonly InputAction m_Default_SweepInput;
    private readonly InputAction m_Default_SwipeInput;
    private readonly InputAction m_Default_DashInput;
    private readonly InputAction m_Default_EscapeTrashBallInput;
    private readonly InputAction m_Default_MouseMoveInput;
    private readonly InputAction m_Default_MouseDeltaInput;
    public struct DefaultActions
    {
        private @PlayerControls m_Wrapper;
        public DefaultActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveInput => m_Wrapper.m_Default_MoveInput;
        public InputAction @SweepInput => m_Wrapper.m_Default_SweepInput;
        public InputAction @SwipeInput => m_Wrapper.m_Default_SwipeInput;
        public InputAction @DashInput => m_Wrapper.m_Default_DashInput;
        public InputAction @EscapeTrashBallInput => m_Wrapper.m_Default_EscapeTrashBallInput;
        public InputAction @MouseMoveInput => m_Wrapper.m_Default_MouseMoveInput;
        public InputAction @MouseDeltaInput => m_Wrapper.m_Default_MouseDeltaInput;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @MoveInput.started += instance.OnMoveInput;
            @MoveInput.performed += instance.OnMoveInput;
            @MoveInput.canceled += instance.OnMoveInput;
            @SweepInput.started += instance.OnSweepInput;
            @SweepInput.performed += instance.OnSweepInput;
            @SweepInput.canceled += instance.OnSweepInput;
            @SwipeInput.started += instance.OnSwipeInput;
            @SwipeInput.performed += instance.OnSwipeInput;
            @SwipeInput.canceled += instance.OnSwipeInput;
            @DashInput.started += instance.OnDashInput;
            @DashInput.performed += instance.OnDashInput;
            @DashInput.canceled += instance.OnDashInput;
            @EscapeTrashBallInput.started += instance.OnEscapeTrashBallInput;
            @EscapeTrashBallInput.performed += instance.OnEscapeTrashBallInput;
            @EscapeTrashBallInput.canceled += instance.OnEscapeTrashBallInput;
            @MouseMoveInput.started += instance.OnMouseMoveInput;
            @MouseMoveInput.performed += instance.OnMouseMoveInput;
            @MouseMoveInput.canceled += instance.OnMouseMoveInput;
            @MouseDeltaInput.started += instance.OnMouseDeltaInput;
            @MouseDeltaInput.performed += instance.OnMouseDeltaInput;
            @MouseDeltaInput.canceled += instance.OnMouseDeltaInput;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @MoveInput.started -= instance.OnMoveInput;
            @MoveInput.performed -= instance.OnMoveInput;
            @MoveInput.canceled -= instance.OnMoveInput;
            @SweepInput.started -= instance.OnSweepInput;
            @SweepInput.performed -= instance.OnSweepInput;
            @SweepInput.canceled -= instance.OnSweepInput;
            @SwipeInput.started -= instance.OnSwipeInput;
            @SwipeInput.performed -= instance.OnSwipeInput;
            @SwipeInput.canceled -= instance.OnSwipeInput;
            @DashInput.started -= instance.OnDashInput;
            @DashInput.performed -= instance.OnDashInput;
            @DashInput.canceled -= instance.OnDashInput;
            @EscapeTrashBallInput.started -= instance.OnEscapeTrashBallInput;
            @EscapeTrashBallInput.performed -= instance.OnEscapeTrashBallInput;
            @EscapeTrashBallInput.canceled -= instance.OnEscapeTrashBallInput;
            @MouseMoveInput.started -= instance.OnMouseMoveInput;
            @MouseMoveInput.performed -= instance.OnMouseMoveInput;
            @MouseMoveInput.canceled -= instance.OnMouseMoveInput;
            @MouseDeltaInput.started -= instance.OnMouseDeltaInput;
            @MouseDeltaInput.performed -= instance.OnMouseDeltaInput;
            @MouseDeltaInput.canceled -= instance.OnMouseDeltaInput;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnMoveInput(InputAction.CallbackContext context);
        void OnSweepInput(InputAction.CallbackContext context);
        void OnSwipeInput(InputAction.CallbackContext context);
        void OnDashInput(InputAction.CallbackContext context);
        void OnEscapeTrashBallInput(InputAction.CallbackContext context);
        void OnMouseMoveInput(InputAction.CallbackContext context);
        void OnMouseDeltaInput(InputAction.CallbackContext context);
    }
}
